### ISSUE TITLE
New application name

### ISSUE THREAD

**Issue by Neox63** [Liinkiing/discord-blindtest-bot#4]
I saw that u needed an application name on README.md, what about something like Blindcord ? 

Very cool bot btw !

**Comment by Liinkiing** [comment]
I forgot to update the README, it's name is **Klee**, like the Genshin Impact character 
![giphy (1)](https://user-images.githubusercontent.com/17753997/109483241-4b700580-7a7f-11eb-9f95-9dac9f8a541c.gif)

But thanks for the suggestion!
