### ISSUE TITLE
Typescript compilation error

### ISSUE THREAD

**Issue by Hamashi** [Liinkiing/discord-blindtest-bot#5]
i get the following error when launching the application : 
'async' modifier cannot be used with 'abstract' modifier

**Comment by Liinkiing** [comment]
Should be fixed with https://github.com/Liinkiing/discord-blindtest-bot/commit/7ceb0607303c3939099b9612bd21e85fbea1725d, I've also upgraded all the deps, so maybe try redoing a yarn / npm install, it should be good 👍
